### ISSUE TITLE
Error applying with default values: commonName: Too long: must have at most 64 bytes

### ISSUE THREAD

**Issue by discordianfish** [jkroepke/helm-charts#37]
Deploying using tf like this:

```hcl
resource "helm_release" "aws_pod_identity_webhook" {
  name       = "aws-pod-identity-webhook"
  repository = "https://jkroepke.github.io/helm-charts/"
  chart      = "amazon-eks-pod-identity-webhook"
  namespace  = "kube-system"

  depends_on = [helm_release.cert_manager]
}
```

I get the following error:
```
│ Error: admission webhook "webhook.cert-manager.io" denied the request: spec.commonName: Too long: must have at most 64 bytes
```

I suspect this is because fullname gets truncated to 63 chars while the commonName includes the namespace and .svc: https://github.com/jkroepke/helm-charts/blob/a79b592527513d83db5ff60d23e5791abba56f75/charts/amazon-eks-pod-identity-webhook/templates/certificate.yaml#L9

**Comment by jkroepke** [comment]
I guess chaging this only to fullname may resolve the issue?

**Comment by discordianfish** [comment]
Sorry I didn't get to it. Might on the weekend. But your change LGTM, so should help!
